/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UFieldGroup: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UProgress: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlider: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    UTree: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.10.0_906661d52ef0afdd9cb652b30e67cad9/node_modules/@nuxt/ui/dist/runtime/components/Tree.vue')['default']
  }
}
