services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data_framelia_reference_app:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=framelia_reference_app

volumes:
  postgres_data_framelia_reference_app:
